### ISSUE TITLE
SelectWidget is lacking placeholder

### ISSUE THREAD

**Issue by adrianparvino** [MLH-Fellowship/react-jsonschema-form#89]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The core package uses placeholder as one of the options[1]. This option was not included in the mui theme [2](Find in page "placeholder"), and consequently was also not included in this theme. 

[1] https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/widgets/SelectWidget.js#L94-L96
[2] https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/SelectWidget/SelectWidget.tsx

**Comment by anikethsaha** [comment]
Fixed
